ExamenFinal/Models/ErrorViewModel.cs
using System;

namespace ExamenFinal.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ExamenFinal/Models/Etiqueta.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExamenFinal.Models
{
    public class Etiqueta
    {
        public int Id { get; set; }
        public string Nombre { get; set; }

        public ICollection<EtiquetaNota> EtiquetaNotas { get; set; }
    }
}

ExamenFinal/Models/EtiquetaNota.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExamenFinal.Models
{
    public class EtiquetaNota
    {
        public int EtiquetaId { get; set; }
        public Etiqueta Etiqueta { get; set; }
        public int NotaId { get; set; }
        public Nota Nota { get; set; }
    }
}

ExamenFinal/Models/Nota.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExamenFinal.Models
{
    public class Nota
    {
        public int Id { get; set; }
        public int CreadorId { get; set; }
        public Usuario Creador { get; set; }
        public string Titulo { get; set; }
        public string Contenido { get; set; }
        public DateTime UltimaModificacion { get; set; }
        public ICollection<EtiquetaNota> EtiquetaNotas { get; set; }
        public ICollection<UsuarioNota> UsuarioNotas { get; set; }
    }
}

ExamenFinal/Models/Usuario.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExamenFinal.Models
{
    public class Usuario
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }

        public ICollection<Nota> Notas { get; set; }
        public ICollection<UsuarioNota> UsuarioNotas { get; set; }
    }
}

ExamenFinal/Models/UsuarioNota.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExamenFinal.Models
{
    public class UsuarioNota
    {
        public int UsuarioId { get; set; }
        public Usuario Usuario { get; set; }
        public int NotaId { get; set; }
        public Nota Nota { get; set; }
    }
}

ExamenFinal/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using ExamenFinal.Models;
using ExamenFinal.Repository;
using ExamenFinal.Service;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;

namespace CalidadT2Tests.Controllers
{
    public class AuthController : Controller
    {
        private readonly IUsuarioRepository user;
        private readonly ICookieAuthService cookie;

        public AuthController(IUsuarioRepository user, ICookieAuthService cookie)
        {
            this.user = user;
            this.cookie = cookie;
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(string username, string password)
        {
            var usuario = user.FindUser(username, password);
            if (usuario != null)
            {
                var claims = new List<Claim> {
                    new Claim(ClaimTypes.Name, username)
                };

                var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                var claimsPrincipal = new ClaimsPrincipal(claimsIdentity);

                cookie.Login(claimsPrincipal);

                return RedirectToAction("Index", "Nota");
            }
            
            ViewBag.Validation = "Usuario y/o contraseña incorrecta";
            return View();
        }

        [HttpGet]
        public IActionResult Registrar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Registrar(string username, string password)
        {
            user.Registrar(username, password);
            return RedirectToAction("Login");
        }

        public ActionResult Logout()
        {
            HttpContext.SignOutAsync();
            return RedirectToAction("Login");
        }
    }
}

ExamenFinal/Controllers/EtiquetaController.cs
using ExamenFinal.Models;
using ExamenFinal.Repository;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExamenFinal.Controllers
{
    public class EtiquetaController : Controller
    {
        private IEtiquetaRepository etiquetaRepository;

        public EtiquetaController(IEtiquetaRepository etiquetaRepository)
        {
            this.etiquetaRepository = etiquetaRepository;
        }

        [HttpGet]
        public IActionResult Registrar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Registrar(Etiqueta etiqueta)
        {
            etiquetaRepository.Registrar(etiqueta);
            return RedirectToAction("Index", "Nota");
        }
    }
}

ExamenFinal/Controllers/NotaController.cs
using ExamenFinal.Models;
using ExamenFinal.Repository;
using ExamenFinal.Service;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExamenFinal.Controllers
{
    [Authorize]
    public class NotaController : Controller
    {
        private INotaRepository notaRepository;
        private IEtiquetaRepository etiquetaRepository;
        private IUsuarioRepository usuarioRepository;
        private ICookieAuthService cookieService;

        public NotaController(INotaRepository notaRepository, IEtiquetaRepository etiquetaRepository, IUsuarioRepository usuarioRepository, ICookieAuthService cookie)
        {
            this.notaRepository = notaRepository;
            this.etiquetaRepository = etiquetaRepository;
            this.usuarioRepository = usuarioRepository;
            this.cookieService = cookie;
        }
        
        [HttpGet]
        public IActionResult Index(string buscar = "", int etiqueta = 0)
        {
            var notas = notaRepository.Listar(buscar, etiqueta);
            foreach (var nota in notas)
            {
                if (nota.Contenido.Length > 50)
                {
                    nota.Contenido = nota.Contenido.Substring(0, 50);
                }
            }
            ViewBag.Buscar = buscar;
            ViewBag.Etiqueta = etiqueta;
            ViewBag.Etiquetas = etiquetaRepository.Listar();
            return View(notas);
        }

        [HttpGet]
        public IActionResult Detalle(int id)
        {
            var nota = notaRepository.ObtenerPorId(id);
            return View(nota);
        }

        [HttpGet]
        public IActionResult Registrar()
        {
            ViewBag.Etiquetas = etiquetaRepository.Listar();
            return View();
        }

        [HttpPost]
        public IActionResult Registrar(Nota nota, int[] Etiquetas)
        {
            notaRepository.Registrar(nota);
            notaRepository.AsignarEtiquetas(nota, Etiquetas);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Editar(int id)
        {
            var nota = notaRepository.ObtenerPorId(id);
            ViewBag.Etiquetas = etiquetaRepository.Listar();
            return View(nota);
        }

        [HttpPost]
        public IActionResult Editar(int id, Nota nota, int[] Etiquetas)
        {
            notaRepository.Editar(id, nota);
            notaRepository.AsignarEtiquetas(nota, Etiquetas);
            return RedirectToAction("Detalle", new { id = id });
        }

        [HttpGet]
        public IActionResult Eliminar(int id)
        {
            notaRepository.Eliminar(id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Compartir(int id)
        {
            var nota = notaRepository.ObtenerPorId(id);
            var usuarios = usuarioRepository.Listar();
            usuarios.Remove(cookieService.GetUserLogged());
            ViewBag.Usuarios = usuarios;
            return View(nota);
        }

        [HttpPost]
        public IActionResult Compartir(int id, int[] Usuarios)
        {
            notaRepository.Compartir(id, Usuarios);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult CompartidoConmigo()
        {
            var notas = notaRepository.ListarCompartidasConmigo();
            return View(notas);
        }
    }
}

ExamenFinal/Views/Etiqueta/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

ExamenFinal/Views/Etiqueta/Registrar.cshtml
<div class="row">
    <div class="col-12">
        <form action="/etiqueta/registrar" method="post">
            <div class="form-group">
                <label>Nombre</label>
                <input type="text" name="Nombre" class="form-control" autocomplete="off" />
            </div>
            <button type="submit" class="btn btn-primary">Guardar</button>
        </form>
    </div>
</div>

ExamenFinal/Views/Nota/CompartidoConmigo.cshtml
<h1>Compartido conmigo</h1>

<div class="row">
    <div class="col-12 mt-3">
        <ul class="list-group">
            @foreach (var nota in Model)
            {
                <li class="list-group-item">
                    <div class="w-100">
                        <span>@nota.Titulo</span>
                    </div>
                    <p>@nota.Contenido</p>
                    <div class="w-100 text-right">
                        <a class="btn btn-info mr-2" href="/nota/detalle/@nota.Id">Detalle</a>
                    </div>
                </li>
            }
        </ul>
    </div>
</div>

ExamenFinal/Views/Nota/Compartir.cshtml
<h1>Commpartir: @Model.Titulo </h1>

<div class="row">
    <div class="col-6">
        <form action="/nota/compartir/@Model.Id " method="post">
            <div class="form-group">
                <label>Usuarios</label>
                <select class="form-control" multiple name="Usuarios">
                    @foreach (var usuario in ViewBag.Usuarios)
                    {
                        <option value="@usuario.Id">@usuario.Username</option>
                    }
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Guardar</button>
        </form>
    </div>
</div>

ExamenFinal/Views/Nota/Detalle.cshtml
<div class="row">
    <div class="col-12">
        <div class="form-group">
            <label>Titulo</label>
            <input type="text" name="Titulo" class="form-control" value="@Model.Titulo" readonly />
        </div>
        <div class="form-group">
            <label>Contenido</label>
            <textarea name="Contenido" class="form-control" readonly>@Model.Contenido</textarea>
        </div>
        <div class="form-group">
            <label>Ultima fecha de modificacion</label>
            <input type="datetime" class="form-control" value="@Model.UltimaModificacion" readonly />
        </div>
        <div class="form-group">
            <label>Etiquetas</label>
            <ul class="list-group">
                @foreach (var etiquetaNota in Model.EtiquetaNotas)
                {
                    <li class="list-group-item">@etiquetaNota.Etiqueta.Nombre</li>
                }
            </ul>
        </div>
    </div>
</div>

ExamenFinal/Views/Nota/Editar.cshtml
<div class="row">
    <div class="col-12">
        <form action="/nota/editar/@Model.Id" method="post">
            <div class="form-group">
                <label>Titulo</label>
                <input type="text" name="Titulo" class="form-control" value="@Model.Titulo" autocomplete="off" />
            </div>
            <div class="form-group">
                <label>Contenido</label>
                <textarea name="Contenido" class="form-control">@Model.Contenido</textarea>
            </div>
            <div class="form-group">
                <label>Etiquetas</label>
                <select class="form-select" multiple name="Etiquetas">
                    @foreach (var etiqueta in ViewBag.Etiquetas)
                    {
                        <option value="@etiqueta.Id">@etiqueta.Nombre</option>
                    }
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Guardar</button>
        </form>
    </div>
</div>

ExamenFinal/Views/Nota/Index.cshtml
<div class="row">
    <div class="col-12">
        @if (ViewBag.Buscar != "" || ViewBag.Etiqueta > 0)
        {
            <a href="/nota" class="btn btn-success mb-3">Listar todo</a>
        }

        <form action="/nota" method="get">
            <div class="form-group">
                <label>Buscar</label>
                <input type="text" name="buscar" class="form-control" value="@ViewBag.Buscar" />
            </div>
            <button type="submit" class="btn btn-primary">Buscar</button>
        </form>
    </div>
    <div class="col-4 mt-3">
        <div class="card">
            <div class="card-body">
                <div class="card-title">
                    <h3>Etiquetas</h3>
                </div>
                <div class="list-group">
                    @foreach (var etiqueta in ViewBag.Etiquetas)
                    {
                        <a href="/nota/index?etiqueta=@etiqueta.Id" class="list-group-item list-group-item-action">@etiqueta.Nombre</a>
                    }
                </div>
            </div>
        </div>
    </div>
    <div class="col-8 mt-3">
        <ul class="list-group">
            @foreach (var nota in Model)
            {
                <li class="list-group-item">
                    <div class="w-100">
                        <span>@nota.Titulo</span>
                    </div>
                    <p>@nota.Contenido</p>
                    <div class="w-100 text-right">
                        <a class="btn btn-success mr-2" href="/nota/compartir/@nota.Id">Compartir</a>
                        <a class="btn btn-info mr-2" href="/nota/detalle/@nota.Id">Detalle</a>
                        <a class="btn btn-warning mr-2" href="/nota/editar/@nota.Id">Editar</a>
                        <a class="btn btn-danger" href="/nota/eliminar/@nota.Id">Eliminar</a>
                    </div>
                </li>
            }
        </ul>
    </div>
</div>

ExamenFinal/Views/Nota/Registrar.cshtml
<div class="row">
    <div class="col-12">
        <form action="/nota/registrar" method="post">
            <div class="form-group">
                <label>Titulo</label>
                <input type="text" name="Titulo" class="form-control" autocomplete="off" />
            </div>
            <div class="form-group">
                <label>Contenido</label>
                <textarea name="Contenido" class="form-control"></textarea>
            </div>
            <div class="form-group">
                <label>Etiquetas</label>
                <select class="form-select" multiple name="Etiquetas">
                    @foreach (var etiqueta in ViewBag.Etiquetas)
                    {
                        <option value="@etiqueta.Id">@etiqueta.Nombre</option>
                    }
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Guardar</button>
        </form>
    </div>
</div>

ExamenFinal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExamenFinal</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ExamenFinal</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Nota" asp-action="Index">Notas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Nota" asp-action="Registrar">Registrar nota</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Etiqueta" asp-action="Registrar">Registrar etiqueta</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Nota" asp-action="CompartidoConmigo">Compartido Conmigo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Logout">Cerrar sesion</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    
    <div class="container body-content">
        <br />
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>
    
    @RenderSection("Scripts", required: false)
</body>
</html>

ExamenFinal/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExamenFinal</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

</head>
<body>
    
    <nav class="navbar navbar-expand-lg">
        <a class="navbar-brand" href="#">Examen Final</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login">Iniciar sesion</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Registrar">Registrarme</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container body-content">
        <br />
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    

</body>
</html>